### ISSUE TITLE
what's the difference between max_energy and max_voxel_energy?

### ISSUE THREAD

**Issue by bigdimboom** [dgrzech/sobfu#10]
![image](https://user-images.githubusercontent.com/6119906/58374255-49bbfa00-7f09-11e9-886f-d91cc2699e73.png)

![image](https://user-images.githubusercontent.com/6119906/58374257-53456200-7f09-11e9-85e5-6368575468f3.png)

**Comment by dgrzech** [comment]
one finds the voxel where the update norm at a given iteration of gradient descent is maximum. the other one finds the voxel where the energy functional has the highest value
