### ISSUE TITLE
can you clarify variable names 

### ISSUE THREAD

**Issue by bigdimboom** [dgrzech/sobfu#5]
is global_phi is the canonical tsdf volume?
what is phi_n in the paper literature?
what's phi_n_psi?
what's phi_global_psi_inv?

**Comment by dgrzech** [comment]
hi! same notation as in the paper--phi_global is the canonical tsdf, phi_n is the live projective sdf, phi_n_psi is the live projective sdf after applying the deformation field, and phi_global_psi_inv is the canonical tsdf after applying the inverse deformation field
