### ISSUE TITLE
why 48?

### ISSUE THREAD

**Issue by bigdimboom** [dgrzech/sobfu#6]
There is a magic number 48 in your code. Can you you explain why you need a loop(48) here?
![image](https://user-images.githubusercontent.com/6119906/57808249-f4296580-7730-11e9-8e53-f54cfe759c51.png)

**Comment by dgrzech** [comment]
a heuristic, 48 was enough for the inverse deformation field to converge https://www.ncbi.nlm.nih.gov/pubmed/18293565
